# Generated by Django 4.2.3 on 2023-09-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskManager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="sprint", name="id",),
        migrations.AlterField(
            model_name="sprint",
            name="sprintName",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
