# Generated by Django 4.2.3 on 2023-09-28 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taskManager", "0002_remove_sprint_id_alter_sprint_sprintname"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "taskName",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("taskDescription", models.CharField(max_length=200)),
                ("taskAssignee", models.CharField(max_length=200)),
                ("taskPoints", models.IntegerField()),
                ("taskState", models.CharField(max_length=200)),
                (
                    "sprintName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taskManager.sprint",
                    ),
                ),
            ],
        ),
    ]
