# Generated by Django 4.2.3 on 2023-09-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskManager", "0003_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="taskAssignee",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="task",
            name="taskDescription",
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="task",
            name="taskName",
            field=models.CharField(max_length=5000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="taskState",
            field=models.CharField(max_length=1000),
        ),
    ]
