# Generated by Django 4.2.3 on 2023-09-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "taskManager",
            "0004_alter_task_taskassignee_alter_task_taskdescription_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="taskName",
            field=models.TextField(max_length=5000, primary_key=True, serialize=False),
        ),
    ]
